### ISSUE TITLE
Carried Objects hold velocities/forces

### ISSUE THREAD

**Issue by hollowspecter** [Shepphard/TheUnnamedProject#11]
Pick up an object and "press it against a wall", that way there is tension, which is a force away from the wall. When you now release the object, the object will fly a different direction than you wanted it to be!

How to solve
Right before you are going to release it, make sure that the objects rigidbody components velocity is the 0-vector, or like "reset" all the forces on the object somehow.

**Comment by Shepphard** [comment]
The cube is actually falling in the correct direction if it hits the wall, while being dropped. It hits the wall, it is falling away from the wall starting from the point it touches the wall.
