### ISSUE TITLE
Object should face the player at any time

### ISSUE THREAD

**Issue by Shepphard** [Shepphard/TheUnnamedProject#13]
The picked up Object should face the player with the same face at any time.

Align the z axis of the object with the z component of the camera.

**Comment by Shepphard** [comment]
More explanation: Object should, while moving the mouse, still show the same face and rotation.

**Comment by hollowspecter** [comment]
Solved by making the object while it is carried a child from the main camera. as soon as it is released, the parent of the carriedObject is put to "null" again hence its back in the main hierarchy
